FROM python:3.10-slim

WORKDIR /app

# Ставим зависимости
COPY voice_service/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код (весь проект, чтобы видеть core)
COPY . /app

# Запуск
CMD ["python", "voice_service/main.py"]